---
abstract: 'Portably generate config for any shell'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: '0.94'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.003, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Shell-Config-Generate
requires:
  Shell::Guess: '0.02'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/plicease/Shell-Config-Generate/issues
  homepage: http://perl.wdlabs.com/Shell-Config-Generate
  repository: git://github.com/plicease/Shell-Config-Generate.git
version: '0.25'
